### ISSUE TITLE
Peer problem Got xian-network-1 expected xian-network

### ISSUE THREAD

**Issue by StianNOR** [xian-network/xian-core#322]
1|cometbft  | E[2024-11-10|02:39:59.586] Couldn't connect to any seeds                module=p2p 
1|cometbft  | I[2024-11-10|02:40:29.479] Ensure peers                                 module=pex numOutPeers=0 numInPeers=0 numDialing=0 numToDial=10
1|cometbft  | I[2024-11-10|02:40:29.479] No addresses to dial. Falling back to seeds  module=pex 
1|cometbft  | E[2024-11-10|02:40:29.590] Error dialing seed                           module=p2p err="incompatible: peer is on a different network. Got xian-network-1, expected xian-network" seed=9c5705850e0e9c67ba382a7e952cec299fa5b656@188.68.33.32:26656
1|cometbft  | E[2024-11-10|02:40:29.590] Couldn't connect to any seeds                module=p2p

Something i did wrong or ?

**Comment by crosschainer** [comment]
there is a upcoming hardfork where we will provide a new genesis block. this issue is caused by using the wrong genesis block. the master branch is currently different from what is being used on the main network, but will be updated after the hardfork
